mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=exitouser
    - MYSQL_PASSWORD=Pa$$w0rd
    - MYSQL_DATABASE=exitodb
  volumes:
    - "./etc/mysql/conf.d:ro"
