INSERT INTO vets VALUES (1, 'James', 'Carter');
INSERT INTO vets VALUES (2, 'Helen', 'Leary');
INSERT INTO vets VALUES (3, 'Linda', 'Douglas');
INSERT INTO vets VALUES (4, 'Rafael', 'Ortega');
INSERT INTO vets VALUES (5, 'Henry', 'Stevens');
INSERT INTO vets VALUES (6, 'Sharon', 'Jenkins');

INSERT INTO specialties VALUES (1, 'radiology');
INSERT INTO specialties VALUES (2, 'surgery');
INSERT INTO specialties VALUES (3, 'dentistry');

INSERT INTO vet_specialties VALUES (2, 1);
INSERT INTO vet_specialties VALUES (3, 2);
INSERT INTO vet_specialties VALUES (3, 3);
INSERT INTO vet_specialties VALUES (4, 2);
INSERT INTO vet_specialties VALUES (5, 1);

INSERT INTO types VALUES (1, 'cat');
INSERT INTO types VALUES (2, 'dog');
INSERT INTO types VALUES (3, 'lizard');
INSERT INTO types VALUES (4, 'snake');
INSERT INTO types VALUES (5, 'bird');
INSERT INTO types VALUES (6, 'hamster');

INSERT INTO owners VALUES (1, 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023');
INSERT INTO owners VALUES (2, 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749');
INSERT INTO owners VALUES (3, 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763');
INSERT INTO owners VALUES (4, 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198');
INSERT INTO owners VALUES (5, 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765');
INSERT INTO owners VALUES (6, 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654');
INSERT INTO owners VALUES (7, 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387');
INSERT INTO owners VALUES (8, 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683');
INSERT INTO owners VALUES (9, 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435');
INSERT INTO owners VALUES (10, 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487');

INSERT INTO pets VALUES (1, 'Leo', '2010-09-07', 1, 1);
INSERT INTO pets VALUES (2, 'Basil', '2012-08-06', 6, 2);
INSERT INTO pets VALUES (3, 'Rosy', '2011-04-17', 2, 3);
INSERT INTO pets VALUES (4, 'Jewel', '2010-03-07', 2, 3);
INSERT INTO pets VALUES (5, 'Iggy', '2010-11-30', 3, 4);
INSERT INTO pets VALUES (6, 'George', '2010-01-20', 4, 5);
INSERT INTO pets VALUES (7, 'Samantha', '2012-09-04', 1, 6);
INSERT INTO pets VALUES (8, 'Max', '2012-09-04', 1, 6);
INSERT INTO pets VALUES (9, 'Lucky', '2011-08-06', 5, 7);
INSERT INTO pets VALUES (10, 'Mulligan', '2007-02-24', 2, 8);
INSERT INTO pets VALUES (11, 'Freddy', '2010-03-09', 5, 9);
INSERT INTO pets VALUES (12, 'Lucky', '2010-06-24', 2, 10);
INSERT INTO pets VALUES (13, 'Sly', '2012-06-08', 1, 10);

INSERT INTO visits VALUES (1, 7, '2013-01-01', 'rabies shot');
INSERT INTO visits VALUES (2, 8, '2013-01-02', 'rabies shot');
INSERT INTO visits VALUES (3, 8, '2013-01-03', 'neutered');
INSERT INTO visits VALUES (4, 7, '2013-01-04', 'spayed');

INSERT INTO usuarios VALUES (1, 'jperez', 'password', 'DonBosco', 'Juan', 'Perez', '2000-06-24', 'masculino', '6to', 'secundaria', 'La Paz', 'Murillo', 'Ciudad de La Paz', 'descripcion aqui', 'jperez@mail.com');

INSERT INTO promedios VALUES (1, '2013-01-04', 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3);

INSERT INTO carrera VALUES (1, 'licenciatura', 'Informática', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (2, 'licenciatura', 'Matemáticas', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (3, 'licenciatura', 'Matemática', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (4, 'licenciatura', 'Matemática', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (5, 'licenciatura', 'Estadística', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (6, 'licenciatura', 'Sociología', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (7, 'licenciatura', 'Biología', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (8, 'licenciatura', 'Biología', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (9, 'licenciatura', 'Biología', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (10, 'licenciatura', 'Biología', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (11, 'licenciatura', 'Química', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (12, 'licenciatura', 'Química', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (13, 'licenciatura', 'Química Industrial', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (14, 'licenciatura', 'Química', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (15, 'licenciatura', 'Ingeniería Ambiental', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (16, 'licenciatura', 'Ingeniería Agroforestal', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (17, 'licenciatura', 'Topografía Y Geodesia', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (18, 'licenciatura', 'Ingeniería Geológica', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (19, 'licenciatura', 'Ingeniería Geológica', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (20, 'licenciatura', 'Ingeniería Geológica', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (21, 'licenciatura', 'Ingeniería del Medio Ambiente', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (22, 'licenciatura', 'Ingeniería Electrónica', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (23, 'licenciatura', 'Idiomas', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (24, 'licenciatura', 'Literatura', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (25, 'licenciatura', 'Inglés', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (26, 'licenciatura', 'Francés', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (27, 'licenciatura', 'Diseño Gráfico', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (28, 'licenciatura', 'Diseño Gráfico', 'Cochabamba', 'Cochabamba', 'Universidad Privada Boliviana', 'UPB', 'Humanidades', 'Privado');
INSERT INTO carrera VALUES (29, 'licenciatura', 'Diseño Gráfico y Comunicación Visual', 'La Paz', 'Ciudad de La Paz', 'Universidad Católica Boliviana San Pablo', 'UCB', 'Humanidades', 'Privado');
INSERT INTO carrera VALUES (30, 'licenciatura', 'Diseño Gráfico', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Privada de Santa Cruz de la Sierra', 'UPSA', 'Humanidades', 'Privado');
INSERT INTO carrera VALUES (31, 'licenciatura', 'Filosofía', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (32, 'licenciatura', 'Filosofía y Letras', 'Cochabamba', 'Cochabamba', 'Universidad Católica Boliviana San Pablo', 'UCB', 'Humanidades', 'Privado');
INSERT INTO carrera VALUES (33, 'licenciatura', 'Lingüística Aplicada a la Enseñanza de Lenguas', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (34, 'licenciatura', 'Lingüística e Idiomas', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (35, 'licenciatura', 'Historia', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (36, 'licenciatura', 'Ingeniería Mecánica', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (37, 'licenciatura', 'Ingeniería Comercial', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (38, 'licenciatura', 'Ingeniería Electromecánica', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (39, 'licenciatura', 'Ingeniería Mecánica', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (40, 'licenciatura', 'Ingeniería Electromecánica', 'Cochabamba', 'Cochabamba', 'Universidad Privada Boliviana', 'UPB', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (41, 'licenciatura', 'Ingeniería Electrónica', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (42, 'licenciatura', 'Ingeniería Mecánica', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (43, 'licenciatura', 'Ingeniería Eléctrica', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (44, 'licenciatura', 'Ingeniería de Sistemas', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (45, 'licenciatura', 'Ingeniería Mecánica', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (46, 'licenciatura', 'Ingeniería de Sistemas', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Privada de Santa Cruz de la Sierra', 'UPSA', 'Tecnología', 'Privado');
INSERT INTO carrera VALUES (47, 'licenciatura', 'Ingeniería Informática', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (48, 'licenciatura', 'Ingeniería Gas Y Petroquímica', 'La Paz', 'Ciudad de El Alto', 'Universidad Pública de El Alto', 'UPEA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (49, 'licenciatura', 'Ingeniería Financiera', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (50, 'Técnico Superior', 'Mecánica Automotriz', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Servicios', 'Publico');
INSERT INTO carrera VALUES (51, 'licenciatura', 'Ingeniería de Sistemas', 'La Paz', 'Ciudad de La Paz', 'Universidad Católica Boliviana San Pablo', 'UCB', 'Tecnología', 'Privado');
INSERT INTO carrera VALUES (52, 'licenciatura', 'Ingeniería de Sistemas', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Católica Boliviana San Pablo', 'UCB', 'Tecnología', 'Privado');
INSERT INTO carrera VALUES (53, 'licenciatura', 'Ingeniería de Sistemas', 'Cochabamba', 'Cochabamba', 'Universidad Católica Boliviana San Pablo', 'UCB', 'Tecnología', 'Privado');
INSERT INTO carrera VALUES (54, 'licenciatura', 'Ingeniería de Sistemas', 'Tarija', 'Tarija', 'Universidad Católica Boliviana San Pablo', 'UCB', 'Tecnología', 'Privado');
INSERT INTO carrera VALUES (55, 'Técnico Superior', 'Mecánica Automotriz', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Servicios', 'Publico');
INSERT INTO carrera VALUES (56, 'licenciatura', 'Ingeniería de Minas', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (57, 'Técnico Superior', 'Mecánica Automotriz', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Servicios', 'Publico');
INSERT INTO carrera VALUES (58, 'licenciatura', 'Ingeniería de Sistemas Computacionales', 'Cochabamba', 'Cochabamba', 'Universidad Privada Boliviana', 'UPB', 'Tecnología', 'Privado');
INSERT INTO carrera VALUES (59, 'licenciatura', 'Ingeniería Comercial', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (60, 'licenciatura', 'Ingeniería de Sistemas', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (61, 'licenciatura', 'Ingeniería Electrónica', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (62, 'licenciatura', 'Ingeniería Textil', 'La Paz', 'Ciudad de El Alto', 'Universidad Pública de El Alto', 'UPEA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (63, 'licenciatura', 'Ingeniería Industrial', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (64, 'licenciatura', 'Ingeniería Informática', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (65, 'licenciatura', 'Ingeniería de Sistemas Electrónicos', 'La Paz', 'Ciudad de La Paz', 'Escuela Militar de Ingeniería', 'EMI', 'Tecnología', 'Privado');
INSERT INTO carrera VALUES (66, 'licenciatura', 'Ingeniería Civil', 'Cochabamba', 'Cochabamba', 'Universidad Privada Boliviana', 'UPB', 'Tecnología', 'Privado');
INSERT INTO carrera VALUES (67, 'licenciatura', 'Electricidad Industrial', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (68, 'licenciatura', 'Ingeniería Electrónica y de Sistemas', 'Cochabamba', 'Cochabamba', 'Universidad Privada del Valle', 'UNIVALLE', 'Tecnología', 'Privado');
INSERT INTO carrera VALUES (69, 'licenciatura', 'Ingeniería de Control de Procesos', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (70, 'licenciatura', 'Ingeniería Química', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (71, 'licenciatura', 'Ingeniería de Alimentos', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (72, 'licenciatura', 'Ingeniería Ambiental', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (73, 'licenciatura', 'Ingeniería Industrial', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (74, 'licenciatura', 'Diseño de Interiores y Paisajismo', 'Cochabamba', 'Cochabamba', 'Universidad Privada del Valle', 'UNIVALLE', 'Servicios', 'Privado');
INSERT INTO carrera VALUES (75, 'licenciatura', 'Ingeniería Comercial', 'Beni', 'Riberalta', 'Escuela Militar de Ingeniería', 'EMI', 'Ciencias Sociales', 'Privado');
INSERT INTO carrera VALUES (76, 'licenciatura', 'Ingeniería Eléctrica', 'La Paz', 'Ciudad de El Alto', 'Universidad Pública de El Alto', 'UPEA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (77, 'licenciatura', 'Ingeniería Agroidustrial', 'Beni', 'Riberalta', 'Escuela Militar de Ingeniería', 'EMI', 'Ciencias Agropecuarias', 'Privado');
INSERT INTO carrera VALUES (78, 'licenciatura', 'Ingeniería Metalúrgica y de Materiales', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (79, 'Técnico Superior', 'Contaduría Pública', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (80, 'licenciatura', 'Ciencias Políticas', 'La Paz', 'Ciudad de El Alto', 'Universidad Pública de El Alto', 'UPEA', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (81, 'Técnico Superior', 'Administración de Empresas', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (82, 'licenciatura', 'Gestión de Negocios', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (83, 'licenciatura', 'Ingeniería Comercial', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (84, 'licenciatura', 'Gestión Pública', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (85, 'licenciatura', 'Comercio Internacional', 'Cochabamba', 'Cochabamba', 'Universidad Privada del Valle', 'UNIVALLE', 'Ciencias Sociales', 'Privado');
INSERT INTO carrera VALUES (86, 'licenciatura', 'Comercio Internacional', 'La Paz', 'Ciudad de La Paz', 'Universidad Privada del Valle', 'UNIVALLE', 'Ciencias Sociales', 'Privado');
INSERT INTO carrera VALUES (87, 'licenciatura', 'Comercio Internacional', 'Chuquisaca', 'Las Delicias', 'Universidad Privada del Valle', 'UNIVALLE', 'Ciencias Sociales', 'Privado');
INSERT INTO carrera VALUES (88, 'licenciatura', 'Comercio Internacional', 'Beni', 'El Gran Paitití', 'Universidad Privada del Valle', 'UNIVALLE', 'Ciencias Sociales', 'Privado');
INSERT INTO carrera VALUES (89, 'licenciatura', 'Comercio Internacional', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Privada de Santa Cruz de la Sierra', 'UPSA', 'Ciencias Sociales', 'Privado');
INSERT INTO carrera VALUES (90, 'licenciatura', 'Ingeniería Comercial', 'Cochabamba', 'Cochabamba', 'Universidad Privada Boliviana', 'UPB', 'Ciencias Sociales', 'Privado');
INSERT INTO carrera VALUES (91, 'licenciatura', 'Ciencias Políticas', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (92, 'licenciatura', 'Ingeniería Agronómica', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (93, 'licenciatura', 'Ingeniería en Prod y Comercialización Agropecuaria', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (94, 'licenciatura', 'Medicina Veterinaria y Zootecnia', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (95, 'licenciatura', 'Arquitectura', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (96, 'licenciatura', 'Artes Plásticas', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (97, 'Técnico Superior', 'Artes Musicales', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (98, 'licenciatura', 'Contaduría Pública', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (99, 'licenciatura', 'Administración de Empresas', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (100, 'licenciatura', 'Economía', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (101, 'licenciatura', 'Antropología', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (102, 'licenciatura', 'Arqueología', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (103, 'licenciatura', 'Comunicación Social', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (104, 'licenciatura', 'Trabajo Social', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Salud', 'Publico');
INSERT INTO carrera VALUES (105, 'licenciatura', 'Derecho', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (106, 'licenciatura', 'C Políticas y Gestión Pública', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (107, 'licenciatura', 'Ciencias de la Educación', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (108, 'licenciatura', 'Bibliotecología', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (109, 'licenciatura', 'Psicología', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (110, 'licenciatura', 'Turismo', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (111, 'licenciatura', 'Ingeniería Civil', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (112, 'licenciatura', 'Ingeniería Petrolera', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (113, 'licenciatura', 'Medicina', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Salud', 'Publico');
INSERT INTO carrera VALUES (114, 'licenciatura', 'Enfermería', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Salud', 'Publico');
INSERT INTO carrera VALUES (115, 'licenciatura', 'Nutrición y Dietética', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Salud', 'Publico');
INSERT INTO carrera VALUES (116, 'licenciatura', 'Tecnología Médica', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (117, 'licenciatura', 'Odontología', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Salud', 'Publico');
INSERT INTO carrera VALUES (118, 'licenciatura', 'Aeronáutica', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (119, 'licenciatura', 'Construcciones Civiles', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (120, 'licenciatura', 'Electricidad Industrial', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (121, 'licenciatura', 'ELectrónica y Telecomunicaciones', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (122, 'licenciatura', 'Mecánica Automotriz', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (123, 'licenciatura', 'Mecánica Industrial', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (124, 'licenciatura', 'Geodesia, Topografúa y Geométrica', 'La Paz', 'Ciudad de La Paz', 'Universidad Mayor de San Andres', 'UMSA', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (125, 'licenciatura', 'Ciencias Jurídicas', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (126, 'licenciatura', 'Ciencias Políticas', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (127, 'licenciatura', 'Psicología', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (128, 'licenciatura', 'Ciencias de la Educación', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (129, 'licenciatura', 'Lingüística aplicada a la enseñanza en lenguas', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (130, 'licenciatura', 'Comunicación Social', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (131, 'licenciatura', 'Trabajo Social', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Salud', 'Publico');
INSERT INTO carrera VALUES (132, 'licenciatura', 'Actividad Física y Deportes', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Servicios', 'Publico');
INSERT INTO carrera VALUES (133, 'licenciatura', 'Música', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Servicios', 'Publico');
INSERT INTO carrera VALUES (134, 'licenciatura', 'Educación intercultural Bilingüe', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Servicios', 'Publico');
INSERT INTO carrera VALUES (135, 'licenciatura', 'Arquitectura', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (136, 'licenciatura', 'Diseño Gráfico y Com Social', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (137, 'licenciatura', 'Planificación de Territorio y Medio Ambiente', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (138, 'licenciatura', 'Diseño de Interiores y Mobiliario', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (139, 'licenciatura', 'Turismo', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (140, 'Técnico Superior', 'Construcción', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Servicios', 'Publico');
INSERT INTO carrera VALUES (141, 'Técnico Superior', 'Economía', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (142, 'Técnico Superior', 'Administración de Empresas', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (143, 'Técnico Superior', 'Contaduría Pública', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (144, 'Técnico Superior', 'Ingeniería Comercial', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (145, 'Técnico Superior', 'Ingeniería Financiera', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (146, 'Técnico Superior', 'Ingeniería Eléctrica', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (147, 'Técnico Superior', 'Ingeniería Electrónica', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (148, 'Técnico Superior', 'Ingeniería Electromecánica', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (149, 'Técnico Superior', 'Ingeniería Industrial', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (150, 'Técnico Superior', 'Ingeniería Civil', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (151, 'Técnico Superior', 'Ingeniería Matemática', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (152, 'Técnico Superior', 'Ingeniería Informática', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (153, 'Técnico Superior', 'Ingeniería de Sistemas', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (154, 'Técnico Superior', 'Ingeniería de Alimentos', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (155, 'Técnico Superior', 'Ingeniería Química', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (156, 'Técnico Superior', 'Biología', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (157, 'Técnico Superior', 'Física', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (158, 'Técnico Superior', 'Sociología', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (159, 'Técnico Superior', 'Antropología', 'Cochabamba', 'Cochabamba', 'Universidad Mayor de San Simón', 'UMSS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (160, 'licenciatura', 'Actividad Física', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Servicios', 'Publico');
INSERT INTO carrera VALUES (161, 'licenciatura', 'Administración de Empresas', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (162, 'licenciatura', 'Arquitectura', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (163, 'licenciatura', 'Arte', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (164, 'licenciatura', 'Bioquímica', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Salud', 'Publico');
INSERT INTO carrera VALUES (165, 'licenciatura', 'Ciencias Ambientales', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (166, 'licenciatura', 'Ciencias de la Comunicación', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (167, 'licenciatura', 'Ciencias de la Educación', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (168, 'licenciatura', 'Ciencias Políticas y Adm Pública', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (169, 'licenciatura', 'Comercio Internacional', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (170, 'licenciatura', 'Construcciones Civiles', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Servicios', 'Publico');
INSERT INTO carrera VALUES (171, 'licenciatura', 'Contaduría Pública', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (172, 'licenciatura', 'Derecho', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (173, 'licenciatura', 'Diseño Integral', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (174, 'licenciatura', 'Economía', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (175, 'licenciatura', 'Enfermería', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Salud', 'Publico');
INSERT INTO carrera VALUES (176, 'licenciatura', 'Farmacia', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Salud', 'Publico');
INSERT INTO carrera VALUES (177, 'licenciatura', 'Gestión del Turismo', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (178, 'licenciatura', 'Ingeniería Agrícola', 'Santa Cruz', 'Montero', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (179, 'licenciatura', 'Ingeniería Agronómica', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (180, 'licenciatura', 'Ingeniería Agropecuaria', 'Santa Cruz', 'Montero', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (181, 'licenciatura', 'Ingeniería Civil', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (182, 'licenciatura', 'Ingeniería de Alimentos', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (183, 'licenciatura', 'Ingeniería de Petróleo y Gas Natural', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (184, 'licenciatura', 'Ingeniería Electromecánica', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (185, 'licenciatura', 'Ingeniería en Materiales', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (186, 'licenciatura', 'Ingeniería en Metalurgia', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (187, 'licenciatura', 'Ingeniería en Redes y Telecomunicaciones', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (188, 'licenciatura', 'Ingeniería de Sistemas', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (189, 'licenciatura', 'Ingeniería Forestal', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (190, 'licenciatura', 'Ingeniería Informática', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (191, 'licenciatura', 'Ingeniería Petrolera', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (192, 'licenciatura', 'Ingeniería Química', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (193, 'licenciatura', 'Lenguas Modernas y Filología Hispánica', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (194, 'licenciatura', 'Mecánica General', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Servicios', 'Publico');
INSERT INTO carrera VALUES (195, 'licenciatura', 'Medicina', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Salud', 'Publico');
INSERT INTO carrera VALUES (196, 'licenciatura', 'Medicina Veterinaria y Zootecnia', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (197, 'licenciatura', 'Odontología', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Salud', 'Publico');
INSERT INTO carrera VALUES (198, 'licenciatura', 'Psicología', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Salud', 'Publico');
INSERT INTO carrera VALUES (199, 'licenciatura', 'Sociología', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (200, 'licenciatura', 'Trabajo Social', 'Santa Cruz', 'Ciudad de Santa Cruz', 'Universidad Autónoma Gabriel René Moreno', 'UAGRM', 'Salud', 'Publico');
INSERT INTO carrera VALUES (201, 'licenciatura', 'Turismo', 'Potosí', 'Uyuni', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (202, 'licenciatura', 'Trabajo Social', 'Potosí', 'Uncía', 'Universidad Autónoma Tomás Frías', 'UATF', 'Salud', 'Publico');
INSERT INTO carrera VALUES (203, 'licenciatura', 'Turismo', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (204, 'licenciatura', 'Lingüística e Idiomas', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (205, 'licenciatura', 'Lingüística e Idiomas', 'Potosí', 'Uyuni', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (206, 'licenciatura', 'Ingeniería Agropecuaria', 'Potosí', 'Villazón', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (207, 'licenciatura', 'Medicina Veterinaria y Zootecnia', 'Potosí', 'Tupiza', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (208, 'licenciatura', 'Ingeniería Agronómica', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (209, 'licenciatura', 'Ingeniería Agroindustrial', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (210, 'licenciatura', 'Ingeniería Desarrollo Rural', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (211, 'licenciatura', 'Enfermería', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Salud', 'Publico');
INSERT INTO carrera VALUES (212, 'licenciatura', 'Enfermería', 'Potosí', 'Villazón', 'Universidad Autónoma Tomás Frías', 'UATF', 'Salud', 'Publico');
INSERT INTO carrera VALUES (213, 'licenciatura', 'Artes Musicales', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (214, 'licenciatura', 'Artes Plásticas', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (215, 'licenciatura', 'Estadística', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (216, 'licenciatura', 'Física', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (217, 'licenciatura', 'Economía', 'Potosí', 'Uyuni', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (218, 'licenciatura', 'Administración de Empresas', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (219, 'licenciatura', 'Economía', 'Potosí', 'Uncía', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (220, 'licenciatura', 'Contabilidad y Finanzas', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (221, 'licenciatura', 'Economía', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (222, 'licenciatura', 'Auditoría', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (223, 'licenciatura', 'Contaduría Pública', 'Potosí', 'Tupiza', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (224, 'licenciatura', 'Derecho', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (225, 'licenciatura', 'Derecho', 'Potosí', 'Uncía', 'Universidad Autónoma Tomás Frías', 'UATF', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (226, 'licenciatura', 'Ingeniería Minera', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (227, 'licenciatura', 'Ing de Procesos de Mat Primas Mineras', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (228, 'licenciatura', 'Medicina', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Salud', 'Publico');
INSERT INTO carrera VALUES (229, 'licenciatura', 'Ingeniería Eléctrica', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (230, 'licenciatura', 'Ingeniería Mecatrónica', 'Potosí', 'Ciudad de Potosí', 'Universidad Autónoma Tomás Frías', 'UATF', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (231, 'licenciatura', 'Medicina Veterinaria y Zootecnia', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (232, 'licenciatura', 'Ingeniería Civil', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (233, 'licenciatura', 'Contaduría Pública', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (234, 'licenciatura', 'Turismo Sostenible', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (235, 'licenciatura', 'Administración de Empresas', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (236, 'licenciatura', 'Derecho', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (237, 'licenciatura', 'Trabajo Social', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Salud', 'Publico');
INSERT INTO carrera VALUES (238, 'licenciatura', 'Comunicación Social', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (239, 'licenciatura', 'Medicina', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Salud', 'Publico');
INSERT INTO carrera VALUES (240, 'licenciatura', 'Enfermería', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Salud', 'Publico');
INSERT INTO carrera VALUES (241, 'licenciatura', 'Odontología', 'Pando', 'Cobija', 'Universidad Amazónica de Pando', 'UAP', 'Salud', 'Publico');
INSERT INTO carrera VALUES (242, 'licenciatura', 'Economía', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (243, 'licenciatura', 'Contaduría Pública', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (244, 'licenciatura', 'Administración de Empresas', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (245, 'licenciatura', 'Arquitectura', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (246, 'licenciatura', 'Ingeniería Civil', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (247, 'licenciatura', 'Ingeniería Química', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (248, 'licenciatura', 'Ingeniería de Alimentos', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (249, 'licenciatura', 'Ingeniería Informática', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (250, 'licenciatura', 'Ingeniería Industrial', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (251, 'licenciatura', 'Ingeniería Agronómica', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (252, 'licenciatura', 'Ingeniería Forestal', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (253, 'licenciatura', 'Ingeniería de Medio Ambiente', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (254, 'licenciatura', 'Enfermería', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Salud', 'Publico');
INSERT INTO carrera VALUES (255, 'licenciatura', 'Bioquímica', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (256, 'licenciatura', 'Química Farmacéutica', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Salud', 'Publico');
INSERT INTO carrera VALUES (257, 'licenciatura', 'Psicología', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Salud', 'Publico');
INSERT INTO carrera VALUES (258, 'licenciatura', 'Odontología', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Salud', 'Publico');
INSERT INTO carrera VALUES (259, 'licenciatura', 'Idiomas', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (260, 'licenciatura', 'Derecho', 'Tarija', 'Ciudad de Tarija', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (261, 'licenciatura', 'Comercio Internacional', 'Tarija', 'Bermejo', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (262, 'licenciatura', 'Contaduría Pública', 'Tarija', 'Bermejo', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (263, 'licenciatura', 'Ingeniería Agropecuaria', 'Tarija', 'Bermejo', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (264, 'licenciatura', 'Ingeniería de Sistemas', 'Tarija', 'Bermejo', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (265, 'licenciatura', 'Administración y Gestión Pública', 'Tarija', 'Gran Chaco', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (266, 'licenciatura', 'Ingeniería Agronómica', 'Tarija', 'Gran Chaco', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (267, 'licenciatura', 'Contaduría Pública', 'Tarija', 'Gran Chaco', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (268, 'licenciatura', 'Ingeniería Informática', 'Tarija', 'Gran Chaco', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (269, 'licenciatura', 'Ingeniería Comercial', 'Tarija', 'Gran Chaco', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (270, 'licenciatura', 'Ingeniería en Recursos Hídricos', 'Tarija', 'Gran Chaco', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (271, 'licenciatura', 'Ingeniería Sanitaria y Ambiental', 'Tarija', 'Gran Chaco', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (272, 'licenciatura', 'Ingeniería Petroquímica', 'Tarija', 'Villamontes', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (273, 'licenciatura', 'Ingeniería en Petróleo y Gas Natural', 'Tarija', 'Villamontes', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (274, 'licenciatura', 'Medicina Veterinaria y Zootecnia', 'Tarija', 'Gran Chaco', 'Universidad Autónoma Juan Misael Saracho', 'UAJMS', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (275, 'licenciatura', 'Medicina Veterinaria y Zootecnia', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (276, 'licenciatura', 'Ingeniería Agronómica', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (277, 'licenciatura', 'Ingeniería Agropecuaria', 'Beni', 'Magdalena', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (278, 'licenciatura', 'Ingeniería Agropecuaria', 'Beni', 'San Borja', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (279, 'licenciatura', 'Ingeniería Agropecuaria', 'Beni', 'Guayaramerin', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (280, 'licenciatura', 'Ingeniería de Sistemas', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (281, 'licenciatura', 'Ingeniería Civil', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (282, 'licenciatura', 'Enfermería', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Salud', 'Publico');
INSERT INTO carrera VALUES (283, 'licenciatura', 'Bioquímica y Farmacia', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Salud', 'Publico');
INSERT INTO carrera VALUES (284, 'licenciatura', 'Medicina', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Salud', 'Publico');
INSERT INTO carrera VALUES (285, 'licenciatura', 'Administración de Empresas', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (286, 'licenciatura', 'Contaduría Pública', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (287, 'licenciatura', 'Economía', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (288, 'licenciatura', 'Ciencias de la Educación', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (289, 'licenciatura', 'Turismo', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Servicios', 'Publico');
INSERT INTO carrera VALUES (290, 'licenciatura', 'Pedagogía', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (300, 'licenciatura', 'Artes', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (301, 'licenciatura', 'Derecho', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (302, 'licenciatura', 'Comunicación Social', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (303, 'licenciatura', 'Ingeniería Forestal', 'Beni', 'Trinidad', 'Universidad Autónoma del Beni José Ballivián', 'UAB', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (304, 'licenciatura', 'Derecho', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (305, 'licenciatura', 'Comunicación Social', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (306, 'licenciatura', 'Sociología', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (307, 'licenciatura', 'Historia', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (308, 'licenciatura', 'Medicina', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Salud', 'Publico');
INSERT INTO carrera VALUES (309, 'licenciatura', 'Odontología', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Salud', 'Publico');
INSERT INTO carrera VALUES (310, 'licenciatura', 'Bioquímica', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (311, 'licenciatura', 'Química Farmacéutica', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Salud', 'Publico');
INSERT INTO carrera VALUES (312, 'licenciatura', 'Biología', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Ciencias Exactas', 'Publico');
INSERT INTO carrera VALUES (313, 'Técnico Superior', 'Administración Financiera', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (314, 'Técnico Superior', 'Economía', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (315, 'licenciatura', 'Ingeniería Química', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (316, 'licenciatura', 'Ingeniería de Alimentos', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (317, 'licenciatura', 'Ingeniería Ambiental', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (318, 'licenciatura', 'Ingeniería de Petróleo y Gas Natural', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (319, 'licenciatura', 'Ingeniería de Sistemas', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (320, 'licenciatura', 'Ingeniería de Telecomunicaciones', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (321, 'licenciatura', 'Diseño y Animación Digital', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (322, 'licenciatura', 'Ingeniería Agronómica', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (323, 'licenciatura', 'Desarrollo Rural', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (324, 'licenciatura', 'Ingeniería Agroforestal', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (325, 'licenciatura', 'Zootecnia', 'Chuquisaca', 'Muyupampa', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (326, 'licenciatura', 'Diseño y Animación Digital', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (327, 'licenciatura', 'Turismo', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (328, 'licenciatura', 'Pedagogía', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (329, 'licenciatura', 'Psicología', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Salud', 'Publico');
INSERT INTO carrera VALUES (330, 'licenciatura', 'Trabajo Social', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Salud', 'Publico');
INSERT INTO carrera VALUES (331, 'licenciatura', 'Gastronomía', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Servicios', 'Publico');
INSERT INTO carrera VALUES (332, 'licenciatura', 'Enfermería', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Salud', 'Publico');
INSERT INTO carrera VALUES (333, 'licenciatura', 'Enfermería', 'Chuquisaca', 'Padilla', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Salud', 'Publico');
INSERT INTO carrera VALUES (334, 'licenciatura', 'Enfermería', 'Chuquisaca', 'Monteagudo', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Salud', 'Publico');
INSERT INTO carrera VALUES (335, 'licenciatura', 'Bio-Imagenología', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Salud', 'Publico');
INSERT INTO carrera VALUES (336, 'licenciatura', 'Kinesiología y Terapia', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Salud', 'Publico');
INSERT INTO carrera VALUES (337, 'licenciatura', 'Laboratorio Clínico', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Salud', 'Publico');
INSERT INTO carrera VALUES (338, 'licenciatura', 'Nutrición y Dietética', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Salud', 'Publico');
INSERT INTO carrera VALUES (339, 'licenciatura', 'Arquitectura', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (340, 'licenciatura', 'Diseño de Interiores', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (341, 'licenciatura', 'Arte y Diseño', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Humanidades', 'Publico');
INSERT INTO carrera VALUES (342, 'licenciatura', 'Ingeniería Civil', 'Chuquisaca', 'Sucre', 'Universidad Mayor, Real y Pontificia de San Francisco Xavier de Chuquisaca', 'UMSFX', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (343, 'licenciatura', 'Derecho', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (344, 'licenciatura', 'Comunicación Social', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (345, 'licenciatura', 'Antropología', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (346, 'licenciatura', 'Derecho', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (347, 'licenciatura', 'Ingeniería Civil', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (348, 'licenciatura', 'Ingeniería Metalúrgica', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (349, 'licenciatura', 'Ingeniería Mecánica', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (350, 'licenciatura', 'Ingeniería Química', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (351, 'licenciatura', 'Ingeniería de Sistemas', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (352, 'licenciatura', 'Ingeniería Industrial', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Tecnología', 'Publico');
INSERT INTO carrera VALUES (353, 'licenciatura', 'Economía', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (354, 'licenciatura', 'Contaduría Pública', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (355, 'licenciatura', 'Administración de Empresas', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Ciencias Sociales', 'Publico');
INSERT INTO carrera VALUES (356, 'licenciatura', 'Ingeniería Agronómica', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (357, 'licenciatura', 'Ingeniería en Recursos Naturales', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (358, 'licenciatura', 'Ingeniería Zootécnica y Bienestar Animal', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (359, 'licenciatura', 'Ingeniería en Producción Agraria', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Ciencias Agropecuarias', 'Publico');
INSERT INTO carrera VALUES (360, 'licenciatura', 'Arquitectura', 'Oruro', 'Ciudad de Oruro', 'Universidad Técnica de Oruro', 'UTO', 'Humanidades', 'Publico');





